USE [master];

IF DB_ID('ZadanieETL') IS NULL
BEGIN

	CREATE DATABASE [ZadanieETL]
	 CONTAINMENT = NONE
	 ON  PRIMARY
	( NAME = N'ZadanieETL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ZadanieETL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
	 LOG ON
	( NAME = N'ZadanieETL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ZadanieETL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
	 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF;

	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
	EXEC [ZadanieETL].[dbo].[sp_fulltext_database] @action = 'enable'
	end;

	ALTER DATABASE [ZadanieETL] SET ANSI_NULL_DEFAULT OFF;

	ALTER DATABASE [ZadanieETL] SET ANSI_NULLS OFF;

	ALTER DATABASE [ZadanieETL] SET ANSI_PADDING OFF;

	ALTER DATABASE [ZadanieETL] SET ANSI_WARNINGS OFF;

	ALTER DATABASE [ZadanieETL] SET ARITHABORT OFF;

	ALTER DATABASE [ZadanieETL] SET AUTO_CLOSE OFF;

	ALTER DATABASE [ZadanieETL] SET AUTO_SHRINK OFF;

	ALTER DATABASE [ZadanieETL] SET AUTO_UPDATE_STATISTICS ON;

	ALTER DATABASE [ZadanieETL] SET CURSOR_CLOSE_ON_COMMIT OFF;

	ALTER DATABASE [ZadanieETL] SET CURSOR_DEFAULT  GLOBAL;

	ALTER DATABASE [ZadanieETL] SET CONCAT_NULL_YIELDS_NULL OFF;

	ALTER DATABASE [ZadanieETL] SET NUMERIC_ROUNDABORT OFF;

	ALTER DATABASE [ZadanieETL] SET QUOTED_IDENTIFIER OFF;

	ALTER DATABASE [ZadanieETL] SET RECURSIVE_TRIGGERS OFF;

	ALTER DATABASE [ZadanieETL] SET  DISABLE_BROKER;

	ALTER DATABASE [ZadanieETL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;

	ALTER DATABASE [ZadanieETL] SET DATE_CORRELATION_OPTIMIZATION OFF;

	ALTER DATABASE [ZadanieETL] SET TRUSTWORTHY OFF;

	ALTER DATABASE [ZadanieETL] SET ALLOW_SNAPSHOT_ISOLATION OFF;

	ALTER DATABASE [ZadanieETL] SET PARAMETERIZATION SIMPLE;

	ALTER DATABASE [ZadanieETL] SET READ_COMMITTED_SNAPSHOT OFF;

	ALTER DATABASE [ZadanieETL] SET HONOR_BROKER_PRIORITY OFF;

	ALTER DATABASE [ZadanieETL] SET RECOVERY FULL;

	ALTER DATABASE [ZadanieETL] SET  MULTI_USER;

	ALTER DATABASE [ZadanieETL] SET PAGE_VERIFY CHECKSUM;

	ALTER DATABASE [ZadanieETL] SET DB_CHAINING OFF;

	ALTER DATABASE [ZadanieETL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF );

	ALTER DATABASE [ZadanieETL] SET TARGET_RECOVERY_TIME = 60 SECONDS;

	ALTER DATABASE [ZadanieETL] SET DELAYED_DURABILITY = DISABLED;

	ALTER DATABASE [ZadanieETL] SET ACCELERATED_DATABASE_RECOVERY = OFF;

	ALTER DATABASE [ZadanieETL] SET QUERY_STORE = ON;

	ALTER DATABASE [ZadanieETL] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON);

	ALTER DATABASE [ZadanieETL] SET  READ_WRITE;

END;
